### ISSUE TITLE
incorrect highlighting for some C<< ... >> format

### ISSUE THREAD

**Issue by cognominal** [MadcapJake/language-perl6fe#13]
C<< QAST::Op.new(:op<say>, QAST::SVal.new(value<Hi!>)) >>
thx again for this module.

**Comment by MadcapJake** [comment]
I'm not sure what this is supposed to be highlighted as?  Are you talking about Pod code formatting?

**Comment by cognominal** [comment]
Yes, I should have made that clear

**Comment by MadcapJake** [comment]
And you want to use double angle brackets as the delimiters? Is this another one of those any-delimiter-works kind of things? :stuck_out_tongue:

**Comment by cognominal** [comment]
A more realistic example would be :

C<< QAST::Op.new(:op<someop>, QAST::SVal.new(value)) >>

Note the :op<someop> which led to the double texas quoting  C<< ...>>
I don't mind if atom replaces the doubled texas quote chars by the appropriare unicode chars
I can't remember how to get them from my keyboard
