### ISSUE TITLE
Test functions

### ISSUE THREAD

**Issue by hankache** [MadcapJake/language-perl6fe#29]
![test](https://cloud.githubusercontent.com/assets/15119547/15798804/dc27945c-2a4e-11e6-97eb-6415eff3bc8d.png)
As shown in the screen shot, the test functions `cmp-ok`, `can-ok` and `does-ok` are not highlighted. In addition the function `is` is being highlighted as if it was a trait.

**Comment by MadcapJake** [comment]
I could make `is` highlight as a function when it's the first thing on a line (or preceded by an opening delimiter).  I don't want to lose `is` being highlighted as a keyword when applying traits. Though perhaps it would look alright as a function.  I'll do some experimenting.

**Comment by MadcapJake** [comment]
However, what if someone has their function declaration separated over a few lines:

``` perl6
sub foo(Str $a, Str $b, Int $c)
    is rw
    is export
{
    $a ~ $b + $c
}
```

That would highlight `is` as a function if I followed the heuristic described in my previous comment.

**Comment by MadcapJake** [comment]
@hankache after some consideration, I can't think of a good rule for when `is` is a trait_mod op and when it's a Test function. Let me know if you think of something that could work.
