### ISSUE TITLE
Syntax Highlight Wrong

### ISSUE THREAD

**Issue by zoffixznet** [MadcapJake/language-perl6fe#4]
Hey,

I notice `$u<value> < $u<denomination>` is incorrectly highlighted.

![highlight](https://cloud.githubusercontent.com/assets/5747918/11719253/e6fdbd5a-9f27-11e5-8a3d-1f042d4ff543.png)

I'm not sure when I last updated the plugin, so sorry if this is already fixed in never version.

**Comment by zoffixznet** [comment]
Here's another example:
![highlight2](https://cloud.githubusercontent.com/assets/5747918/11719999/5f0c584e-9f2b-11e5-96ac-155dc78f8931.png)

**Comment by MadcapJake** [comment]
Just pushed a fix for both, thanks!

**Comment by zoffixznet** [comment]
Thanks. FWIW, it seems the description of the plugin in Atom is messed up:

![description](https://cloud.githubusercontent.com/assets/5747918/11721728/4ff49080-9f33-11e5-98ee-d657c465cd46.png)

**Comment by MadcapJake** [comment]
lol, I don't know why it can't read my "descirption"! :wink: https://github.com/MadcapJake/language-perl6fe/blob/master/package.json#L4

**Comment by MadcapJake** [comment]
I'm glad another bug was found, for some reason having the version be `1.2.3` was bothering me :stuck_out_tongue_closed_eyes:
