### ISSUE TITLE
DEPRECATE?

### ISSUE THREAD

**Issue by ryanerwin** [MadcapJake/language-perl6fe#55]
language-perl6fe hasn't been updated for over a year, meanwhile, language-perl6 is being actively updated...

yet on atom's package installer, there are 5 x as many users on the language-perl6FE...

perhaps it would be good to officially deprecate this language-perl6fe in favor of migrating users over to language-perl6

for me, I found the existence of both very confusing... if you do decide to deprecate, ideally you could remove "language-perl6fe" from the atom packge list.

**Comment by samcv** [comment]
@MadcapJake see you merged some of my PR for your meta info on perl 6 modules. Would you be able to deprecate this or at least give a link and say the currently worked on project is `language-perl6` on atom.io?

**Comment by samcv** [comment]
@MadcapJake if you can grant me collaborator status on this repo, I can make the changes for you if that is fine with you. You may be busy and I'd like to do whatever is the easiest way to get this done! Thank you!~

**Comment by MadcapJake** [comment]
Thanks but I've added a note to the repo. BTW, thanks for taking the project over and apologies for the untimely responses on my part.

Anyone know what the protocol is for deprecating apm packages? Perhaps there is some way to show a deprecation warning upon installing or better yet a "sidegrade" update that uninstalls this and installs the official package.

**Comment by samcv** [comment]
@MadcapJake I think I've about figured it out. Will make a PR. Not finding any documentation for a way to *uninstall* packages. but we can make it depend on the new package, and deactivate the grammar.

**Comment by MadcapJake** [comment]
Thanks for the help @samcv! I just pushed v2.0.0 to apm.
