### ISSUE TITLE
Broken highlights in term names where 1 char follows apostrophe/hyphen

### ISSUE THREAD

**Issue by zoffixznet** [MadcapJake/language-perl6fe#7]
Hey,

See screenshot below. Seems to only happen when just a single char follows the approstrophe:
![bug3](https://cloud.githubusercontent.com/assets/5747918/11793632/b3c11b66-a27a-11e5-8a4b-3d90cfba82f8.png)

**Comment by zoffixznet** [comment]
Found a new more examples actually:
![bug5](https://cloud.githubusercontent.com/assets/5747918/11793665/ec25acba-a27a-11e5-85c6-e3b67fed40ca.png)
![bug4](https://cloud.githubusercontent.com/assets/5747918/11793666/ec45a2ea-a27a-11e5-8033-9cc6f666c2b1.png)

**Comment by MadcapJake** [comment]
that second one is weird, but I specifically avoided allowing apostrophes until someone brought it up. So here it is! I'll give it a go then, wish me luck.

**Comment by MadcapJake** [comment]
oh actually the second one is because I required that you at least have two letters between each dash.  I'll see if I can avoid this but it might clash with simple space-less minus operations

**Comment by zoffixznet** [comment]
If it clashes, then don't worry. I only noticed it while typing a term, and even if it shows up wrong, it's not the end of the world, because it's short.

**Comment by MadcapJake** [comment]
Solved all three cases and I think it shouldn't break anything else.  Since sigils are always prefixing a variable, it makes it a bit easier on the highlighter to decipher when something is a space-less expression.

**Comment by MadcapJake** [comment]
Fixed in v1.2.4
